#!/usr/bin/env bash
set -e -o pipefail

TEST_FILTER="${TEST_FILTER:-}"
TEST_SKIP_INTEGRATION_CLI=1

# skip autogen step that isn't necessary for balena-engine
sed -i '/source "${MAKEDIR}\/.go-autogen"/d' \
    hack/make/.integration-test-helpers

. hack/make/.balena-env
. hack/make/.integration-test-helpers

PATH="$DEST/balena-engine:$PATH"
# the integration tests will have this location hardcoded
mkdir -p /usr/local/cli
ln -sv "$DEST/balena-engine/balena-engine" /usr/local/cli/balena-engine

(
    build_test_suite_binaries
    bundle .integration-daemon-start
    bundle .integration-daemon-setup

    run_test_integration
    testexit=$?

    bundle .integration-daemon-stop
    cleanup_test_suite_binaries
    error_on_leaked_containerd_shims

    exit ${testexit}
)
